### ISSUE TITLE
Discuss in details about time factor for the cars

### ISSUE THREAD

**Issue by therimalaya** [cssd2019/trafficjam#5]
Thanks to the templete created by @CMJones001, it made easy to write code and concentrate directly on the problem. Currently, with the help of @garethgillard we tried to compute the distance as `self.velocity ^ 2 / self.retardation_rate` where we assumed _one_ as a time unit. So that if `safe_distance` is less than this distance we hit the brake and if `safe_distance` is more than this distance and if the car has not reached the maximum speed, it accelerates.

We need to test this with different case scenarios and also discuss a few things on the time factor as a whole.

https://github.com/cssd2019/trafficjam/blob/a9341daf2d4e0a56b4a9974ccc7c44a6fc5c2184/source/car.py#L34-L50

**Comment by garethgillard** [comment]
A quick note to think about. If the safe_distance we calculate to be the minimal distance before the car needs to slows down, then if the distance_to_next_car is < the safe_distance, we need to slow done (so need to change  that < sign (or the variables) around).

**Comment by therimalaya** [comment]
With the help of @dgrell and @woailao, I have implemented a simple version of the position update method for cars. I think I will close the issue for now.
